### ISSUE TITLE
Error in test cases while building LD2NL project

### ISSUE THREAD

**Issue by AparnaSivaprasad** [dice-group/LD2NL#2]
Hello,

I am getting the following error while executing 'mvn clean install' in LD2NL.
![error](https://user-images.githubusercontent.com/10527382/99567478-81a4e000-29ce-11eb-8a21-3e22fd800ff5.PNG)
I have also added the test report for the failing test cases below.
[org.aksw.sparql2nl.SPARQL2NLTest.txt](https://github.com/dice-group/LD2NL/files/5561814/org.aksw.sparql2nl.SPARQL2NLTest.txt)

I am working with a Windows 10 system and using Java version 1.8.0_271 and Maven version 3.6.3.
Please help me with this issue.

**Comment by renespeck** [comment]
Hi, thanks for the report. 

Any need to install the application? 

Please try: `mvn clean compile`

**Comment by AparnaSivaprasad** [comment]
Thanks for your reply.
'mvn clean compile' builds the code successfully.
I previously used the install command since it was mentioned in the Setup section in OWL2NL wiki.
However, the test cases still fail if 'mvn clean verify' is executed.
